[package]
authors = ["Siegfried Weber <mail@siegfriedweber.net>"]
description = "Stackable Agent Integration tests"
edition = "2018"
license = "Apache-2.0"
name = "agent-integration-tests"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
futures = "0.3"
indoc = "1"
k8s-openapi = { version = "0.11", default-features = false, features = ["v1_20"] }
kube = "0.51"
kube-derive = "0.51"
kube-runtime = "0.51"
schemars = "0.8"
serde = "1"
serde_json = "1"
serde_yaml = "0.8"
spectral = "0.6"
tokio = { version = "1", features = ["rt-multi-thread"] }
uuid = { version = "0.8", features = ["v4"] }
